# Generated by Django 5.2.17 on 2026-09-02 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import garden.models.photos


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HarvestUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, unique=True)),
                ('start_month', models.PositiveSmallIntegerField()),
                ('start_day', models.PositiveSmallIntegerField(default=1)),
                ('end_month', models.PositiveSmallIntegerField()),
                ('end_day', models.PositiveSmallIntegerField(default=28)),
                ('is_builtin', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_month', 'start_day'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('short_code', models.CharField(blank=True, max_length=10)),
                ('sun_notes', models.TextField(blank=True)),
                ('soil_notes', models.TextField(blank=True)),
                ('irrigation_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bed_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garden.bedtype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=garden.models.photos.photo_upload_path)),
                ('taken_on', models.DateField(blank=True, null=True)),
                ('season', models.CharField(blank=True, choices=[('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall')], max_length=6)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='garden.photocategory')),
            ],
            options={
                'ordering': ['-taken_on', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('botanical_name', models.CharField(blank=True, max_length=200)),
                ('cultivar', models.CharField(blank=True, max_length=200)),
                ('is_edible', models.BooleanField(default=False)),
                ('is_ornamental', models.BooleanField(default=True)),
                ('foliage', models.CharField(blank=True, choices=[('evergreen', 'Evergreen'), ('deciduous', 'Deciduous'), ('semi', 'Semi-evergreen')], max_length=10)),
                ('sun', models.CharField(blank=True, choices=[('full', 'Full sun'), ('part', 'Part sun/shade'), ('shade', 'Shade')], max_length=6)),
                ('water_needs', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=8)),
                ('soil_notes', models.TextField(blank=True)),
                ('mature_height', models.CharField(blank=True, max_length=60)),
                ('mature_width', models.CharField(blank=True, max_length=60)),
                ('toxicity_notes', models.TextField(blank=True)),
                ('planted_on', models.DateField(blank=True, null=True)),
                ('planted_precision', models.CharField(choices=[('exact', 'Exact date'), ('month', 'Month known'), ('year', 'Year known')], default='exact', max_length=5)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('removed', 'Removed'), ('died', 'Died')], default='active', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('watch_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(blank=True, related_name='plants', to='garden.photo')),
                ('primary_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='garden.photo')),
                ('plant_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garden.planttype')),
                ('bloom_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='garden.seasonwindow')),
                ('fertilize_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='garden.seasonwindow')),
                ('harvest_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='garden.seasonwindow')),
                ('prune_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='garden.seasonwindow')),
                ('tags', models.ManyToManyField(blank=True, to='garden.tag')),
            ],
            options={
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='HarvestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvested_on', models.DateField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=9)),
                ('intended_use', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garden.harvestunit')),
                ('photos', models.ManyToManyField(blank=True, related_name='harvests', to='garden.photo')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='garden.plant')),
            ],
            options={
                'ordering': ['-harvested_on'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_on', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garden.activitytype')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='garden.bed')),
                ('photos', models.ManyToManyField(blank=True, related_name='activities', to='garden.photo')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='garden.plant')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-performed_on'],
            },
        ),
        migrations.CreateModel(
            name='PlantLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_note', models.CharField(blank=True, max_length=200)),
                ('is_current', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plant_locations', to='garden.bed')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='garden.plant')),
            ],
            options={
                'ordering': ['-is_current', '-started_on'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beds', models.ManyToManyField(blank=True, related_name='journal_entries', to='garden.bed')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(blank=True, related_name='journal_entries', to='garden.photo')),
                ('plants', models.ManyToManyField(blank=True, related_name='journal_entries', to='garden.plant')),
                ('tags', models.ManyToManyField(blank=True, to='garden.tag')),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=6)),
                ('schedule_kind', models.CharField(choices=[('exact_once', 'On a date'), ('exact_yearly', 'Same date every year'), ('window_once', 'Once, within a seasonal window'), ('window_yearly', 'Every year, within a seasonal window'), ('interval', 'Repeating every N days/weeks/months')], max_length=14)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('interval_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('interval_unit', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=6)),
                ('interval_anchor', models.CharField(choices=[('after_completion', 'After each completion'), ('fixed', 'From a fixed date')], default='after_completion', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('beds', models.ManyToManyField(blank=True, related_name='tasks', to='garden.bed')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plants', models.ManyToManyField(blank=True, related_name='tasks', to='garden.plant')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garden.tag')),
                ('window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garden.seasonwindow')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garden.taskcategory')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TaskOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_on', models.DateField(blank=True, null=True)),
                ('window_start', models.DateField(blank=True, null=True)),
                ('window_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=9)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('completion_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='garden.activity')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='garden.task')),
            ],
            options={
                'ordering': ['due_on', 'window_start'],
            },
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('name',), name='unique_active_bed_name'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), models.Q(('short_code', ''), _negated=True)), fields=('short_code',), name='unique_active_bed_short_code'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('plant__isnull', False), ('bed__isnull', False), _connector='OR'), name='activity_has_plant_or_bed'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('due_on__isnull', False), ('schedule_kind__in', ['exact_once', 'exact_yearly'])), models.Q(('schedule_kind__in', ['window_once', 'window_yearly']), ('window__isnull', False)), models.Q(('interval_count__isnull', False), ('schedule_kind', 'interval')), _connector='OR'), name='task_timing_fields_match_kind'),
        ),
    ]
