# Generated by Django 5.2.17 on 2026-09-02 22:53

from django.db import migrations, models

import garden.models.photos


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_seed_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=garden.models.photos.photo_upload_path),
        ),
        migrations.AddField(
            model_name='photo',
            name='file_web',
            field=models.ImageField(blank=True, null=True, upload_to=garden.models.photos.photo_upload_path),
        ),
    ]
