# Generated by Django 5.2.17 on 2026-09-04 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_photo_derivatives'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weed', 'Weed'), ('pest', 'Pest'), ('disease', 'Disease / plant health')], max_length=7)),
                ('name', models.CharField(max_length=150)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('identification_notes', models.TextField(blank=True, help_text='Distinguishing features, look-alikes')),
                ('spread_notes', models.TextField(blank=True, help_text='How it spreads / life cycle / conditions that favor it')),
                ('control_notes', models.TextField(blank=True, help_text='Control or treatment methods, removal and disposal details')),
                ('seed_alert', models.BooleanField(default=False, verbose_name='Do not let it go to seed')),
                ('is_beneficial', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('best_control_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garden.seasonwindow')),
                ('photos', models.ManyToManyField(blank=True, related_name='problem_types', to='garden.photo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProblemCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_note', models.CharField(blank=True, max_length=200)),
                ('first_observed', models.DateField()),
                ('last_observed', models.DateField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('isolated', 'Isolated / mild'), ('moderate', 'Moderate'), ('widespread', 'Widespread / severe')], default='isolated', max_length=10)),
                ('status', models.CharField(choices=[('monitoring', 'Monitoring'), ('active', 'Active'), ('treating', 'Treating'), ('improving', 'Improving'), ('controlled', 'Controlled'), ('resolved', 'Resolved')], default='active', max_length=10)),
                ('confidence', models.CharField(choices=[('unknown', 'Unknown'), ('possible', 'Possible'), ('likely', 'Likely'), ('confirmed', 'Confirmed')], default='unknown', max_length=9)),
                ('symptoms', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_on', models.DateField(blank=True, help_text='Re-inspection date; surfaces on Today', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='problem_cases', to='garden.bed')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(blank=True, related_name='problem_cases', to='garden.photo')),
                ('plants', models.ManyToManyField(blank=True, related_name='problem_cases', to='garden.plant')),
                ('problem_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='garden.problemtype')),
            ],
            options={
                'ordering': ['-first_observed'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treated_on', models.DateField()),
                ('method', models.CharField(help_text='Pulled, sprayed neem, pruned out, corrected watering...', max_length=200)),
                ('product', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('effectiveness', models.CharField(choices=[('unknown', 'Too early to tell'), ('worked', 'Worked'), ('partial', 'Partly worked'), ('failed', 'Did not work')], default='unknown', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='garden.problemcase')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(blank=True, related_name='treatments', to='garden.photo')),
            ],
            options={
                'ordering': ['-treated_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='problemtype',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('kind', 'name'), name='unique_active_problem_type'),
        ),
    ]
