# Generated by Django 5.2.17 on 2026-09-04 03:01

from django.db import migrations, models

import garden.models.property_map


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_problemtype_problemcase_treatment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=garden.models.property_map.aerial_upload_path)),
                ('is_primary', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('opacity', models.FloatField(default=1.0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(default=1000)),
                ('height', models.FloatField(default=750)),
                ('grid_cols', models.PositiveSmallIntegerField(default=10)),
                ('grid_rows', models.PositiveSmallIntegerField(default=8)),
                ('grid_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'property map',
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='boundary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantlocation',
            name='point_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantlocation',
            name='point_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
