# Generated by Django 5.2.17 on 2026-09-04 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_aisuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardiness_zone', models.CharField(blank=True, max_length=10)),
                ('avg_last_frost_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avg_last_frost_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avg_first_frost_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avg_first_frost_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('botanical_name', models.CharField(blank=True, max_length=150)),
                ('cultivar', models.CharField(blank=True, max_length=100)),
                ('crop_family', models.CharField(blank=True, choices=[('nightshade', 'Nightshade'), ('brassica', 'Brassica'), ('legume', 'Legume'), ('cucurbit', 'Cucurbit'), ('allium', 'Allium'), ('root', 'Root crop'), ('leafy', 'Leafy green'), ('herb', 'Herb'), ('other', 'Other')], max_length=10)),
                ('days_to_maturity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('spacing_notes', models.CharField(blank=True, max_length=200)),
                ('start_indoors_weeks_before_lf', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='start indoors (weeks before last frost)')),
                ('transplant_weeks_after_lf', models.SmallIntegerField(blank=True, null=True, verbose_name='transplant outdoors (weeks after last frost)')),
                ('direct_sow_weeks', models.SmallIntegerField(blank=True, null=True, verbose_name='direct sow (weeks after last frost, negative = before)')),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'varieties',
                'ordering': ['name', 'cultivar'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('controller_station', models.PositiveSmallIntegerField(blank=True, help_text='Station number on the controller, when known.', null=True)),
                ('zone_type', models.CharField(choices=[('spray', 'Spray'), ('rotor', 'Rotor'), ('drip', 'Drip'), ('bubbler', 'Bubbler'), ('manual', 'Hose / manual'), ('mixed', 'Mixed'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('investigation_status', models.CharField(choices=[('unknown', 'Unknown'), ('partially_mapped', 'Partially mapped'), ('mapped', 'Mapped'), ('verified', 'Verified')], default='unknown', max_length=20)),
                ('schedule_notes', models.TextField(blank=True, help_text='Typical runtime, seasonal changes, controller program.')),
                ('last_verified_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('needs_repair', 'Needs repair'), ('seasonal', 'Seasonal'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beds', models.ManyToManyField(blank=True, related_name='irrigation_zones', to='garden.bed')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('head', 'Sprinkler head'), ('emitter', 'Drip emitter'), ('valve', 'Valve'), ('controller', 'Controller'), ('shutoff', 'Shutoff'), ('backflow', 'Backflow device'), ('pipe', 'Pipe / line'), ('other', 'Other')], max_length=10)),
                ('location_note', models.CharField(blank=True, help_text='e.g. "NE corner, behind the rhododendron"', max_length=200)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('needs_adjustment', 'Needs adjustment'), ('leaking', 'Leaking'), ('clogged', 'Clogged'), ('broken', 'Broken'), ('buried', 'Buried / missing'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('model_info', models.CharField(blank=True, help_text='Manufacturer / model / nozzle, when known.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_components', to='garden.bed')),
                ('photos', models.ManyToManyField(blank=True, related_name='irrigation_components', to='garden.photo')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='garden.irrigationzone')),
            ],
            options={
                'ordering': ['component_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('task_due', 'Task due'), ('task_overdue', 'Task overdue'), ('problem_followup', 'Problem follow-up'), ('seasonal', 'Seasonal')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('link_path', models.CharField(blank=True, max_length=300)),
                ('dedupe_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('lead_days', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'notification prefs',
            },
        ),
        migrations.CreateModel(
            name='SeasonalPlanting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('started_indoors', 'Started indoors'), ('hardening', 'Hardening off'), ('planted', 'Planted'), ('finished', 'Finished')], default='planned', max_length=15)),
                ('growing_method', models.CharField(choices=[('seed_indoors', 'Start seeds indoors'), ('direct_sow', 'Direct sow'), ('purchase_starts', 'Purchase starts'), ('undecided', 'Undecided')], default='undecided', max_length=15)),
                ('planned_quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sowed_on', models.DateField(blank=True, null=True)),
                ('transplanted_on', models.DateField(blank=True, null=True)),
                ('first_harvest_on', models.DateField(blank=True, null=True)),
                ('last_harvest_on', models.DateField(blank=True, null=True)),
                ('grow_again', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=5)),
                ('season_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantings', to='garden.bed')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantings', to='garden.variety')),
            ],
            options={
                'ordering': ['-year', 'variety__name'],
            },
        ),
        migrations.AddField(
            model_name='harvestevent',
            name='seasonal_planting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='garden.seasonalplanting'),
        ),
        migrations.CreateModel(
            name='IrrigationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('repair', 'Repair'), ('observation', 'Observation'), ('schedule_change', 'Schedule change'), ('startup', 'Spring startup'), ('winterization', 'Winterization'), ('other', 'Other')], max_length=15)),
                ('happened_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='garden.irrigationcomponent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(blank=True, related_name='irrigation_events', to='garden.photo')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='garden.irrigationzone')),
            ],
            options={
                'ordering': ['-happened_on'],
                'constraints': [models.CheckConstraint(condition=models.Q(('zone__isnull', False), ('component__isnull', False), _connector='OR'), name='irrigation_event_has_zone_or_component')],
            },
        ),
    ]
