# Generated by Django 5.2.17 on 2026-09-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_climateprofile_variety_irrigationzone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='natural_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='natural_width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
