# Generated by Django 5.2.17 on 2026-09-05 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0008_maplayer_natural_height_maplayer_natural_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My garden', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='bed',
            name='unique_active_bed_name',
        ),
        migrations.RemoveConstraint(
            model_name='bed',
            name='unique_active_bed_short_code',
        ),
        migrations.RemoveConstraint(
            model_name='problemtype',
            name='unique_active_problem_type',
        ),
        migrations.AddField(
            model_name='garden',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='bed',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='climateprofile',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='harvestevent',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='irrigationcomponent',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='irrigationevent',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='notification',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='photo',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='plant',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='problemcase',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='problemtype',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='seasonalplanting',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='task',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='variety',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('garden', 'name'), name='unique_active_bed_name'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), models.Q(('short_code', ''), _negated=True)), fields=('garden', 'short_code'), name='unique_active_bed_short_code'),
        ),
        migrations.AddConstraint(
            model_name='problemtype',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('garden', 'kind', 'name'), name='unique_active_problem_type'),
        ),
        migrations.AddConstraint(
            model_name='garden',
            constraint=models.UniqueConstraint(fields=('owner',), name='unique_garden_owner'),
        ),
    ]
