# Generated by Django 5.2.17 on 2026-09-05 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0010_backfill_gardens'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
        migrations.AddField(
            model_name='propertymap',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='garden.garden'),
        ),
    ]
