# Generated by Django 5.2.17 on 2026-09-05 02:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0011_maplayer_garden_propertymap_garden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='shared_gardens', to=settings.AUTH_USER_MODEL),
        ),
    ]
