# Generated by Django 5.2.17 on 2026-09-06 19:37

import django.db.models.deletion
from django.db import migrations, models


def classify_existing_layers_as_aerial(apps, schema_editor):
    apps.get_model("garden", "MapLayer").objects.update(kind="aerial")


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0012_garden_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='canvas_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='canvas_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='canvas_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='canvas_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='immutable_original',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='kind',
            field=models.CharField(choices=[('master', 'Master property map'), ('aerial', 'Aerial / historical imagery'), ('reference', 'Other reference imagery')], default='reference', max_length=12),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='source_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='garden.maplayer'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='version',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            classify_existing_layers_as_aerial,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='maplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'master')), fields=('garden', 'version'), name='unique_master_map_version_per_garden'),
        ),
        migrations.AddConstraint(
            model_name='maplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('kind', 'master'), ('archived_at__isnull', True)), fields=('garden',), name='one_active_master_map_per_garden'),
        ),
    ]
