# Generated by Django 5.2.17 on 2026-09-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0013_maplayer_canvas_height_maplayer_canvas_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='fall_care',
            field=models.TextField(blank=True, help_text='What to do in fall, including cleanup, dividing, planting, or protection.', verbose_name='fall care'),
        ),
        migrations.AddField(
            model_name='plant',
            name='problems_to_watch',
            field=models.TextField(blank=True, help_text='Likely pests, diseases, or stress signs and what to look for.', verbose_name='problems to watch for'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pruning_recommendations',
            field=models.TextField(blank=True, help_text='When and how to prune this plant, including important cautions.'),
        ),
        migrations.AddField(
            model_name='plant',
            name='spring_care',
            field=models.TextField(blank=True, help_text='What to do in spring, including feeding, cleanup, watering, or support.', verbose_name='spring care'),
        ),
        migrations.AddField(
            model_name='plant',
            name='summer_care',
            field=models.TextField(blank=True, help_text='What to do in summer, including watering, deadheading, or harvest care.', verbose_name='summer care'),
        ),
        migrations.AddField(
            model_name='plant',
            name='winter_care',
            field=models.TextField(blank=True, help_text='What to do in winter, including dormancy care and weather protection.', verbose_name='winter care'),
        ),
    ]
