# Generated by Django 5.2.17 on 2026-09-10 03:17

from django.db import migrations, models


def tighten_existing_grids(apps, schema_editor):
    PropertyMap = apps.get_model("garden", "PropertyMap")
    for property_map in PropertyMap.objects.all().iterator():
        property_map.grid_cols *= 4
        property_map.grid_rows *= 4
        property_map.save(update_fields=["grid_cols", "grid_rows"])


def restore_existing_grids(apps, schema_editor):
    PropertyMap = apps.get_model("garden", "PropertyMap")
    for property_map in PropertyMap.objects.all().iterator():
        property_map.grid_cols //= 4
        property_map.grid_rows //= 4
        property_map.save(update_fields=["grid_cols", "grid_rows"])


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0014_plant_fall_care_plant_problems_to_watch_and_more'),
    ]

    operations = [
        migrations.RunPython(tighten_existing_grids, restore_existing_grids),
        migrations.AlterField(
            model_name='propertymap',
            name='grid_cols',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='propertymap',
            name='grid_rows',
            field=models.PositiveSmallIntegerField(default=32),
        ),
    ]
