# Generated by Django 5.2.17 on 2026-09-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0015_alter_propertymap_grid_cols_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='beds', to='garden.photo'),
        ),
    ]
