from django.urls import path

from . import (
    views,
    views_ai,
    views_irrigation,
    views_map,
    views_notifications,
    views_planner,
    views_settings,
    views_sharing,
)

urlpatterns = [
    path("", views.today, name="today"),
    path("me/", views.me, name="me"),
    path("garden/switch/", views_sharing.switch_garden, name="garden-switch"),
    path("garden/invite/", views_sharing.invite_member, name="garden-invite"),
    path("garden/members/<int:user_id>/remove/", views_sharing.remove_member,
         name="garden-remove-member"),
    path("plants/", views.plant_list, name="plant-list"),
    path("plants/add/", views.plant_form, name="plant-add"),
    path("plants/<int:pk>/", views.plant_detail, name="plant-detail"),
    path("plants/<int:pk>/edit/", views.plant_form, name="plant-edit"),
    path("plants/<int:pk>/archive/", views.plant_archive, name="plant-archive"),
    path("plants/<int:pk>/unarchive/", views.plant_unarchive, name="plant-unarchive"),
    path("plants/<int:pk>/delete/", views.plant_delete, name="plant-delete"),
    path("plants/<int:pk>/activity/add/", views.activity_add, name="activity-add"),
    path("plants/<int:pk>/harvest/add/", views.harvest_add, name="harvest-add"),
    path("plants/<int:pk>/photos/add/", views.photo_add, name="photo-add"),
    path(
        "plants/<int:pk>/photos/<int:photo_pk>/remove/",
        views.plant_photo_remove,
        name="plant-photo-remove",
    ),
    path(
        "plants/<int:pk>/photos/<int:photo_pk>/make-primary/",
        views.plant_photo_make_primary,
        name="plant-photo-make-primary",
    ),
    path("journal/", views.journal_list, name="journal-list"),
    path("journal/add/", views.journal_add, name="journal-add"),
    path("ai/identify/", views_ai.identify, name="ai-identify"),
    path("ai/lookup/", views_ai.plant_lookup, name="plant-lookup"),
    path("ai/suggestions/<int:pk>/", views_ai.suggestion_detail, name="ai-suggestion"),
    path("assistant/", views_ai.assistant, name="assistant"),
    path("ai/ask/", views_ai.assistant, name="ai-ask"),
    path("plants/<int:pk>/enrich/", views_ai.plant_enrich, name="plant-enrich"),
    path("map/", views_map.map_page, name="map"),
    path("map/data.json", views_map.map_data, name="map-data"),
    path("map/beds/create/", views_map.bed_create_from_outline, name="map-bed-create"),
    path("map/bed/<int:pk>/boundary/", views_map.bed_boundary, name="map-bed-boundary"),
    path("map/plant/<int:pk>/point/", views_map.plant_point, name="map-plant-point"),
    path("map/layers/upload/", views_map.layer_upload, name="map-layer-upload"),
    path(
        "map/master/adopt-preserved/",
        views_map.adopt_preserved_master,
        name="map-master-adopt-preserved",
    ),
    path("map/master/upload/", views_map.master_map_upload, name="map-master-upload"),
    path(
        "map/master/<int:pk>/activate/",
        views_map.master_map_activate,
        name="map-master-activate",
    ),
    path(
        "map/layers/<int:pk>/toggle/",
        views_map.reference_layer_toggle,
        name="map-layer-toggle",
    ),
    path("map/layers/satellite/", views_map.satellite_fetch, name="map-satellite"),
    path("problems/", views.problem_list, name="problem-list"),
    path("problems/add/", views.problem_add, name="problem-add"),
    path("problems/<int:pk>/", views.problem_detail, name="problem-detail"),
    path("problems/<int:pk>/treat/", views.treatment_add, name="treatment-add"),
    path("tasks/", views.task_list, name="task-list"),
    path("tasks/add/", views.task_form, name="task-add"),
    path("tasks/<int:pk>/edit/", views.task_form, name="task-edit"),
    path(
        "occurrences/<int:pk>/<str:action>/",
        views.occurrence_action,
        name="occurrence-action",
    ),
    path("settings/", views_settings.settings_home, name="settings"),
    path("settings/vocab/<slug:slug>/", views_settings.vocab_action, name="settings-vocab"),
    path("settings/windows/", views_settings.window_action, name="settings-window"),
    path("beds/", views_settings.bed_list, name="bed-list"),
    path("beds/add/", views_settings.bed_form, name="bed-add"),
    path("beds/<int:pk>/", views_settings.bed_form, name="bed-edit"),
    path("beds/<int:pk>/archive/", views_settings.bed_archive, name="bed-archive"),
    # Vegetable Garden Planner (#24)
    path("planner/", views_planner.planner_home, name="planner"),
    path("planner/plantings/add/", views_planner.planting_form, name="planting-add"),
    path("planner/plantings/<int:pk>/edit/", views_planner.planting_form, name="planting-edit"),
    path(
        "planner/plantings/<int:pk>/planted/",
        views_planner.mark_planted,
        name="planting-planted",
    ),
    path("planner/plantings/<int:pk>/close/", views_planner.close_planting, name="planting-close"),
    path("planner/varieties/", views_planner.variety_list, name="variety-list"),
    path("planner/varieties/add/", views_planner.variety_form, name="variety-add"),
    path("planner/varieties/<int:pk>/edit/", views_planner.variety_form, name="variety-edit"),
    path("planner/climate/", views_planner.climate_form, name="planner-climate"),
    # Irrigation (#25)
    path("irrigation/", views_irrigation.irrigation_overview, name="irrigation-overview"),
    path("irrigation/zones/add/", views_irrigation.zone_form, name="irrigation-zone-add"),
    path("irrigation/zones/<int:pk>/", views_irrigation.zone_detail,
         name="irrigation-zone-detail"),
    path("irrigation/zones/<int:pk>/edit/", views_irrigation.zone_form,
         name="irrigation-zone-edit"),
    path("irrigation/zones/<int:pk>/archive/", views_irrigation.zone_archive,
         name="irrigation-zone-archive"),
    path("irrigation/components/add/", views_irrigation.component_form,
         name="irrigation-component-add"),
    path("irrigation/components/<int:pk>/edit/", views_irrigation.component_form,
         name="irrigation-component-edit"),
    path("irrigation/events/add/", views_irrigation.event_add, name="irrigation-event-add"),
    # Notifications (#26)
    path("notifications/", views_notifications.center, name="notifications"),
    path(
        "notifications/all-read/",
        views_notifications.mark_all_read,
        name="notifications-all-read",
    ),
    path("notifications/prefs/", views_notifications.prefs_update, name="notifications-prefs"),
    path(
        "notifications/<int:pk>/<str:action>/",
        views_notifications.action,
        name="notification-action",
    ),
]
